services:
  # FrontEnd React Server
  # client:
  #   build: ./src/client
  #   container_name: emissions_client
  #   env_file: .env.example
  #   ports:
  #     - "3000:3000"
  #   # depends_on:
  #   #   - server
    
  # Backend Nest API Server
  # server:
  #   build: ./src/server
  #   container_name: emissions_server
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./src/server:/app
  #     - /app/node_modules
  #   command: npm run start:dev

  # Postgres Database
  postgres:
    image: postgres:16-alpine
    container_name: emissions_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: emissions
      POSTGRES_USER: emissions
      POSTGRES_PASSWORD: emissions
    ports:
      - "5433:5432" # Host port must be open on the device, watch for running postgres process
    volumes:
      - emissions_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20

  # Optional: candidates can choose to use it for idempotency keys, caching, etc.
  # redis:
  #   image: redis:7-alpine
  #   container_name: emissions_redis
  #   restart: unless-stopped
  #   ports:
  #     - "${REDIS_PORT:-6379}:6379"
  #   command: ["redis-server", "--appendonly", "no"]
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 20

  # # Optional: DB admin UI for reviewers/candidates. Safe to keep.
  # # If you don't want extra surface area, remove this service.
  # pgadmin:
  #   image: dpage/pgadmin4:8
  #   container_name: emissions_pgadmin
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@local.dev}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   profiles: ["tools"]

volumes:
  emissions_pg_data: